package mx.blick.training.store
/*
 * This Groovy source file was generated by the Gradle 'init' task.
 */
class Main {
    static void main(String []args) {
        println "Poor's Man store!"
    }
}
