/*
 * This Spock specification was generated by the Gradle 'init' task.
 */

import mx.blick.training.store.Main
import spock.lang.Specification

class MainTest extends Specification {
    def "someLibraryMethod returns true"() {
        setup:
        def lib = new Main()

        when:
        def result = lib

        then:
        true == true
    }
}
